<?php
use Migrations\AbstractSeed;

/**
 * AvailableServices seed.
 */
class AvailableServicesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'requests_type_id' => '3',
                'name' => 'Inspección visual de componentes de revisión técnica',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 13:46:10',
                'modified' => '2017-03-14 13:46:10',
            ],
            [
                'id' => '2',
                'requests_type_id' => '1',
                'name' => 'Reparación por rechazo de revisión técnica',
                'description' => '',
                'estimated_time' => '2',
                'real_estimated_time' => '2',
                'total_price' => '50000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '20000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 13:47:19',
                'modified' => '2017-03-14 13:47:19',
            ],
            [
                'id' => '3',
                'requests_type_id' => '3',
                'name' => 'Sacar revisión técnica',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '75000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '30000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 13:48:19',
                'modified' => '2017-03-14 13:48:19',
            ],
            [
                'id' => '4',
                'requests_type_id' => '2',
                'name' => 'Revisión y preparación de viaje ',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '62500',
                'supplies_price' => '3450',
                'replacements_price' => NULL,
                'mechanic_pay' => '25000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 13:52:35',
                'modified' => '2017-03-14 13:52:35',
            ],
            [
                'id' => '5',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de pastillas de frenos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '3700',
                'replacements_price' => '30000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 13:56:32',
                'modified' => '2017-03-14 13:56:32',
            ],
            [
                'id' => '6',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de discos de freno',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '3700',
                'replacements_price' => '55000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 13:59:18',
                'modified' => '2017-03-14 13:59:18',
            ],
            [
                'id' => '7',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de balatas de freno',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1700',
                'replacements_price' => '35000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:02:38',
                'modified' => '2017-03-14 14:02:38',
            ],
            [
                'id' => '8',
                'requests_type_id' => '1',
                'name' => 'Cambio de tambores o discos traseros',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '3700',
                'replacements_price' => '30000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:04:15',
                'modified' => '2017-03-14 14:04:15',
            ],
            [
                'id' => '9',
                'requests_type_id' => '3',
                'name' => 'Inspección de luces y nivel de liquido de freno',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => '1500',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:05:27',
                'modified' => '2017-03-14 14:06:07',
            ],
            [
                'id' => '10',
                'requests_type_id' => '2',
                'name' => 'Aseo y mantención de frenos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '62500',
                'supplies_price' => '3700',
                'replacements_price' => '1500',
                'mechanic_pay' => '25000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:07:26',
                'modified' => '2017-03-14 14:07:26',
            ],
            [
                'id' => '11',
                'requests_type_id' => '3',
                'name' => 'Revisar luz testigo ABS',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:08:18',
                'modified' => '2017-03-14 14:08:18',
            ],
            [
                'id' => '12',
                'requests_type_id' => '3',
                'name' => 'Revisar luz testigo de freno de mano',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:10:10',
                'modified' => '2017-03-14 14:10:10',
            ],
            [
                'id' => '13',
                'requests_type_id' => '2',
                'name' => 'Regulación freno de mano',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:12:03',
                'modified' => '2017-03-14 14:12:03',
            ],
            [
                'id' => '14',
                'requests_type_id' => '1',
                'name' => 'Sangrar sistema de frenos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:13:26',
                'modified' => '2017-03-14 14:13:26',
            ],
            [
                'id' => '15',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de liquido de frenos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:14:18',
                'modified' => '2017-03-14 14:14:18',
            ],
            [
                'id' => '16',
                'requests_type_id' => '1',
                'name' => 'Rectificado de discos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '50000',
                'supplies_price' => '1700',
                'replacements_price' => NULL,
                'mechanic_pay' => '20000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:16:27',
                'modified' => '2017-03-14 14:16:27',
            ],
            [
                'id' => '17',
                'requests_type_id' => '1',
                'name' => 'Cambio de switch de freno',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '55000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:25:22',
                'modified' => '2017-03-14 14:25:22',
            ],
            [
                'id' => '18',
                'requests_type_id' => '3',
                'name' => 'Chequeo sistema de carga',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:26:44',
                'modified' => '2017-03-14 14:26:44',
            ],
            [
                'id' => '19',
                'requests_type_id' => '3',
                'name' => 'Revisar conexiones de batería',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:30:05',
                'modified' => '2017-03-14 14:30:05',
            ],
            [
                'id' => '20',
                'requests_type_id' => '3',
                'name' => 'Revisar estado de batería',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '2500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:36:18',
                'modified' => '2017-03-14 14:36:18',
            ],
            [
                'id' => '21',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de batería',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1000',
                'replacements_price' => '50000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:37:18',
                'modified' => '2017-03-14 14:37:18',
            ],
            [
                'id' => '22',
                'requests_type_id' => '1',
                'name' => 'Cambiar terminales de batería',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:38:50',
                'modified' => '2017-03-14 14:38:50',
            ],
            [
                'id' => '23',
                'requests_type_id' => '1',
                'name' => 'Desmontar y montar alternador',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '700',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:42:22',
                'modified' => '2017-03-14 14:42:22',
            ],
            [
                'id' => '24',
                'requests_type_id' => '1',
                'name' => 'Cambio de correa de alternador',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '25000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:43:45',
                'modified' => '2017-03-14 14:43:45',
            ],
            [
                'id' => '25',
                'requests_type_id' => '3',
                'name' => 'Revisar sistema de arranque',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:45:10',
                'modified' => '2017-03-14 14:45:10',
            ],
            [
                'id' => '26',
                'requests_type_id' => '1',
                'name' => 'Desmontar y montar motor de partida',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1900',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:47:58',
                'modified' => '2017-03-14 14:47:58',
            ],
            [
                'id' => '27',
                'requests_type_id' => '3',
                'name' => 'Inspección vehículo no enciende',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '37500',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '15000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:52:10',
                'modified' => '2017-03-14 14:59:58',
            ],
            [
                'id' => '28',
                'requests_type_id' => '1',
                'name' => 'Reparar bocina',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1200',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 14:54:21',
                'modified' => '2017-03-14 14:54:21',
            ],
            [
                'id' => '29',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de focos traseros',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '40000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:57:40',
                'modified' => '2017-03-14 14:57:40',
            ],
            [
                'id' => '30',
                'requests_type_id' => '1',
                'name' => 'Reemplazo foco de patente',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '2000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:58:40',
                'modified' => '2017-03-14 14:58:40',
            ],
            [
                'id' => '31',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de neblineros',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 14:59:26',
                'modified' => '2017-03-14 14:59:26',
            ],
            [
                'id' => '32',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de ópticos delanteros',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '4000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:00:54',
                'modified' => '2017-03-14 15:00:54',
            ],
            [
                'id' => '33',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de luces de freno',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:01:47',
                'modified' => '2017-03-14 15:01:47',
            ],
            [
                'id' => '34',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de luces de retroceso',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:03:27',
                'modified' => '2017-03-14 15:03:27',
            ],
            [
                'id' => '35',
                'requests_type_id' => '1',
                'name' => 'Reemplazo luces de señalizadores',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:04:25',
                'modified' => '2017-03-14 15:04:25',
            ],
            [
                'id' => '36',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de espejos exteriores',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '15000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:05:48',
                'modified' => '2017-03-14 15:05:48',
            ],
            [
                'id' => '37',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de luces de interior',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:08:32',
                'modified' => '2017-03-14 15:08:32',
            ],
            [
                'id' => '38',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de luces o ampolletas exteriores',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '1500',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:09:59',
                'modified' => '2017-03-14 15:09:59',
            ],
            [
                'id' => '39',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de fusibles',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '2500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:11:13',
                'modified' => '2017-03-14 15:11:13',
            ],
            [
                'id' => '40',
                'requests_type_id' => '1',
                'name' => 'Cambio de comando de luces',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:12:06',
                'modified' => '2017-03-14 15:12:06',
            ],
            [
                'id' => '41',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de filtro de aire',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:24:49',
                'modified' => '2017-03-14 15:24:49',
            ],
            [
                'id' => '42',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de bobina',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '700',
                'replacements_price' => '15000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:26:13',
                'modified' => '2017-03-14 15:26:13',
            ],
            [
                'id' => '43',
                'requests_type_id' => '1',
                'name' => 'Reemplazo cables de bujías',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '10000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:28:02',
                'modified' => '2017-03-14 15:28:02',
            ],
            [
                'id' => '44',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de bujías',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '5000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:28:43',
                'modified' => '2017-03-14 15:28:43',
            ],
            [
                'id' => '45',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de sensor o actuador',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '7000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:30:53',
                'modified' => '2017-03-14 15:30:53',
            ],
            [
                'id' => '46',
                'requests_type_id' => '2',
                'name' => 'Revisar línea de escape',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:32:07',
                'modified' => '2017-03-14 15:32:07',
            ],
            [
                'id' => '47',
                'requests_type_id' => '2',
                'name' => 'Limpiar cuerpo de aspiración',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '600',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:32:50',
                'modified' => '2017-03-14 15:32:50',
            ],
            [
                'id' => '48',
                'requests_type_id' => '3',
                'name' => 'Revisar perdidas de aceite',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '0',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:35:03',
                'modified' => '2017-03-14 15:35:03',
            ],
            [
                'id' => '49',
                'requests_type_id' => '1',
                'name' => 'Sellar o cambiar empaquetadura de Carter',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '55000',
                'supplies_price' => NULL,
                'replacements_price' => '20500',
                'mechanic_pay' => '22000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:36:28',
                'modified' => '2017-03-14 15:36:28',
            ],
            [
                'id' => '50',
                'requests_type_id' => '1',
                'name' => 'Sellar tapa de válvulas o cambiar empaquetadura',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '50000',
                'supplies_price' => '450',
                'replacements_price' => NULL,
                'mechanic_pay' => '20000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:37:28',
                'modified' => '2017-03-14 15:37:28',
            ],
            [
                'id' => '51',
                'requests_type_id' => '1',
                'name' => 'Soporte de motor',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '80000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:39:23',
                'modified' => '2017-03-14 15:39:23',
            ],
            [
                'id' => '52',
                'requests_type_id' => '3',
                'name' => 'Revisar alarma',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:40:20',
                'modified' => '2017-03-14 15:40:20',
            ],
            [
                'id' => '53',
                'requests_type_id' => '3',
                'name' => 'Revisar centralizado',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:41:05',
                'modified' => '2017-03-14 15:41:05',
            ],
            [
                'id' => '54',
                'requests_type_id' => '3',
                'name' => 'Revisar apertura de puertas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:42:16',
                'modified' => '2017-03-14 15:42:16',
            ],
            [
                'id' => '55',
                'requests_type_id' => '1',
                'name' => 'Cambio o reparación de cilindro de puerta',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '30000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:43:05',
                'modified' => '2017-03-14 15:43:05',
            ],
            [
                'id' => '56',
                'requests_type_id' => '2',
                'name' => 'Revisar o emparejar manos libres',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:44:09',
                'modified' => '2017-03-14 15:44:09',
            ],
            [
                'id' => '57',
                'requests_type_id' => '2',
                'name' => 'Revisar sistemas de audio',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:44:38',
                'modified' => '2017-03-14 15:44:38',
            ],
            [
                'id' => '58',
                'requests_type_id' => '2',
                'name' => 'Lubricar bisagras y puertas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '2200',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:45:26',
                'modified' => '2017-03-14 15:45:26',
            ],
            [
                'id' => '59',
                'requests_type_id' => '2',
                'name' => 'Limpiar y lubricar gomas de corredera',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1200',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:47:09',
                'modified' => '2017-03-14 15:47:09',
            ],
            [
                'id' => '60',
                'requests_type_id' => '1',
                'name' => 'Cambio de switch de alza vidrios',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '35000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:48:33',
                'modified' => '2017-03-14 15:48:33',
            ],
            [
                'id' => '61',
                'requests_type_id' => '1',
                'name' => 'Cambio de vidrio',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '55000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:49:27',
                'modified' => '2017-03-14 15:49:27',
            ],
            [
                'id' => '62',
                'requests_type_id' => '1',
                'name' => 'Reemplazo de plumillas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '750',
                'replacements_price' => '2000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:50:27',
                'modified' => '2017-03-14 15:50:27',
            ],
            [
                'id' => '63',
                'requests_type_id' => '1',
                'name' => 'Ajustar salida liquido limpia parabrisas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:51:25',
                'modified' => '2017-03-14 15:51:25',
            ],
            [
                'id' => '64',
                'requests_type_id' => '1',
                'name' => 'Cambio deposito limpia parabrisas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '35000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:52:07',
                'modified' => '2017-03-14 15:52:07',
            ],
            [
                'id' => '65',
                'requests_type_id' => '3',
                'name' => 'Revisar sistema limpia parabrisas delantero o trasero',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:53:05',
                'modified' => '2017-03-14 15:53:05',
            ],
            [
                'id' => '66',
                'requests_type_id' => '1',
                'name' => 'Cambio de motor de lavaparabrisas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '16000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:54:04',
                'modified' => '2017-03-14 15:54:04',
            ],
            [
                'id' => '67',
                'requests_type_id' => '1',
                'name' => 'Cambio de antena',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '5000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:54:41',
                'modified' => '2017-03-14 15:54:41',
            ],
            [
                'id' => '68',
                'requests_type_id' => '3',
                'name' => 'Revisar defroster',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:55:22',
                'modified' => '2017-03-14 15:55:22',
            ],
            [
                'id' => '69',
                'requests_type_id' => '3',
                'name' => 'Revisar toma eléctrica de 12V',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '700',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 15:56:24',
                'modified' => '2017-03-14 15:56:24',
            ],
            [
                'id' => '70',
                'requests_type_id' => '4',
                'name' => 'Revisión de pre compra',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '35000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '14000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:57:02',
                'modified' => '2017-03-14 19:13:55',
            ],
            [
                'id' => '71',
                'requests_type_id' => '3',
                'name' => 'Luz testigo encendidas con scanner universal Launch',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '37500',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '15000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:57:55',
                'modified' => '2017-03-14 15:57:55',
            ],
            [
                'id' => '72',
                'requests_type_id' => '3',
                'name' => 'Luz de SRS',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 15:59:06',
                'modified' => '2017-03-14 15:59:06',
            ],
            [
                'id' => '73',
                'requests_type_id' => '1',
                'name' => 'Luz de aceite',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:23:26',
                'modified' => '2017-03-14 17:23:26',
            ],
            [
                'id' => '74',
                'requests_type_id' => '1',
                'name' => 'Luz de "Check Engine"',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:25:34',
                'modified' => '2017-03-14 17:25:34',
            ],
            [
                'id' => '75',
                'requests_type_id' => '3',
                'name' => 'Test de fuga de refrigerante por medio de presurización',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 17:28:41',
                'modified' => '2017-03-14 17:28:41',
            ],
            [
                'id' => '76',
                'requests_type_id' => '2',
                'name' => 'Cambio de mangueras',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '3500',
                'replacements_price' => '6000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:30:19',
                'modified' => '2017-03-14 17:40:48',
            ],
            [
                'id' => '77',
                'requests_type_id' => '1',
                'name' => 'Cambio de termostato',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5450',
                'replacements_price' => '8000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:32:49',
                'modified' => '2017-03-14 17:32:49',
            ],
            [
                'id' => '78',
                'requests_type_id' => '2',
                'name' => 'Cambio tapa de radiador',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:34:13',
                'modified' => '2017-03-14 17:40:33',
            ],
            [
                'id' => '79',
                'requests_type_id' => '1',
                'name' => 'Cambio de radiador',
                'description' => '',
                'estimated_time' => '2',
                'real_estimated_time' => '2',
                'total_price' => '50000',
                'supplies_price' => '5450',
                'replacements_price' => '70000',
                'mechanic_pay' => '20000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:38:10',
                'modified' => '2017-03-14 17:38:10',
            ],
            [
                'id' => '80',
                'requests_type_id' => '2',
                'name' => 'Cambio de abrazadera',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5450',
                'replacements_price' => '12000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:39:26',
                'modified' => '2017-03-14 17:40:17',
            ],
            [
                'id' => '81',
                'requests_type_id' => '2',
                'name' => 'Reemplazo de refrigerante',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:40:06',
                'modified' => '2017-03-14 17:40:06',
            ],
            [
                'id' => '82',
                'requests_type_id' => '1',
                'name' => 'Cambio deposito refrigerante',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:44:16',
                'modified' => '2017-03-14 17:44:16',
            ],
            [
                'id' => '83',
                'requests_type_id' => '3',
                'name' => 'Revisar nivel del refrigerante',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 17:46:10',
                'modified' => '2017-03-14 17:46:10',
            ],
            [
                'id' => '84',
                'requests_type_id' => '3',
                'name' => 'Revisar electro ventiladores',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '2500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:51:54',
                'modified' => '2017-03-14 17:51:54',
            ],
            [
                'id' => '85',
                'requests_type_id' => '2',
                'name' => 'Mantención básica',
                'description' => '',
                'estimated_time' => '2',
                'real_estimated_time' => '2',
                'total_price' => '37500',
                'supplies_price' => '10250',
                'replacements_price' => '55000',
                'mechanic_pay' => '15000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 17:55:58',
                'modified' => '2017-03-14 17:55:58',
            ],
            [
                'id' => '86',
                'requests_type_id' => '2',
                'name' => 'Mantención intermedia',
                'description' => '',
                'estimated_time' => '3',
                'real_estimated_time' => '3',
                'total_price' => '50000',
                'supplies_price' => '11950',
                'replacements_price' => '60000',
                'mechanic_pay' => '20000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 17:58:34',
                'modified' => '2017-03-14 17:58:34',
            ],
            [
                'id' => '87',
                'requests_type_id' => '2',
                'name' => 'Mantención completa',
                'description' => '',
                'estimated_time' => '4',
                'real_estimated_time' => '4',
                'total_price' => '75000',
                'supplies_price' => '15750',
                'replacements_price' => '105000',
                'mechanic_pay' => '30000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:00:32',
                'modified' => '2017-03-14 18:00:32',
            ],
            [
                'id' => '88',
                'requests_type_id' => '1',
                'name' => 'Cambio de filtro de cabina (polen)',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:13:16',
                'modified' => '2017-03-14 18:13:16',
            ],
            [
                'id' => '89',
                'requests_type_id' => '3',
                'name' => 'Revisión poco flujo de salida de aire ventilación',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:15:21',
                'modified' => '2017-03-14 18:15:21',
            ],
            [
                'id' => '90',
                'requests_type_id' => '3',
                'name' => 'Revisar T° salida de aire',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:16:39',
                'modified' => '2017-03-14 18:16:39',
            ],
            [
                'id' => '91',
                'requests_type_id' => '1',
                'name' => 'Cambio correa de A/C',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '12000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:17:23',
                'modified' => '2017-03-14 18:17:23',
            ],
            [
                'id' => '92',
                'requests_type_id' => '1',
                'name' => 'Carga de A/C',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => '15000',
                'mechanic_pay' => '25000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:18:12',
                'modified' => '2017-03-14 18:18:12',
            ],
            [
                'id' => '93',
                'requests_type_id' => '2',
                'name' => 'Sanitizacion de cabina y/o limpieza de ductos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:19:26',
                'modified' => '2017-03-14 18:19:26',
            ],
            [
                'id' => '94',
                'requests_type_id' => '3',
                'name' => 'Revisar mandos de calefacción',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:20:40',
                'modified' => '2017-03-14 18:20:40',
            ],
            [
                'id' => '95',
                'requests_type_id' => '1',
                'name' => 'Cambio de resistencia de calefacción',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '30000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:21:17',
                'modified' => '2017-03-14 18:21:17',
            ],
            [
                'id' => '96',
                'requests_type_id' => '2',
                'name' => 'Limpieza de inyectores sin desmontar',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '16000',
                'mechanic_pay' => '25000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:22:33',
                'modified' => '2017-03-14 18:22:33',
            ],
            [
                'id' => '97',
                'requests_type_id' => '3',
                'name' => 'Revisar líneas de combustible',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:23:48',
                'modified' => '2017-03-14 18:23:48',
            ],
            [
                'id' => '98',
                'requests_type_id' => '1',
                'name' => 'Reemplazo filtro de combustible',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1900',
                'replacements_price' => '45000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:24:50',
                'modified' => '2017-03-14 18:24:50',
            ],
            [
                'id' => '99',
                'requests_type_id' => '1',
                'name' => 'Reemplazo pre filtro diésel',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '55000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:26:12',
                'modified' => '2017-03-14 18:26:12',
            ],
            [
                'id' => '100',
                'requests_type_id' => '2',
                'name' => 'Cambio de aceite y filtro',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '5250',
                'replacements_price' => '35000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:27:44',
                'modified' => '2017-03-14 18:27:44',
            ],
            [
                'id' => '101',
                'requests_type_id' => '2',
                'name' => 'Cambio de aceite de transmisión',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '10000',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:30:12',
                'modified' => '2017-03-14 18:30:12',
            ],
            [
                'id' => '102',
                'requests_type_id' => '2',
                'name' => 'Cambio de aceite de diferencial',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '23000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:32:04',
                'modified' => '2017-03-14 18:32:04',
            ],
            [
                'id' => '103',
                'requests_type_id' => '3',
                'name' => 'Revisión nivel de liquidos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '12750',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:33:41',
                'modified' => '2017-03-14 18:33:41',
            ],
            [
                'id' => '104',
                'requests_type_id' => '2',
                'name' => 'Tensar correas',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:34:37',
                'modified' => '2017-03-14 18:34:37',
            ],
            [
                'id' => '105',
                'requests_type_id' => '2',
                'name' => 'Cambiar correa',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '3000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:38:02',
                'modified' => '2017-03-14 18:38:02',
            ],
            [
                'id' => '106',
                'requests_type_id' => '3',
                'name' => 'Revisar ruido en correas, tensar o lubricar',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '1200',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:38:35',
                'modified' => '2017-03-14 18:38:35',
            ],
            [
                'id' => '107',
                'requests_type_id' => '2',
                'name' => 'Reinstalar piezas plásticas ',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '1000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:41:41',
                'modified' => '2017-03-14 18:41:41',
            ],
            [
                'id' => '108',
                'requests_type_id' => '1',
                'name' => 'Instalación de gomas de barra estabilizadora',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '1800',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:42:48',
                'modified' => '2017-03-14 18:42:48',
            ],
            [
                'id' => '109',
                'requests_type_id' => '1',
                'name' => 'Instalación de bieletas de dirección',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '23000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:43:26',
                'modified' => '2017-03-14 18:45:14',
            ],
            [
                'id' => '110',
                'requests_type_id' => '3',
                'name' => 'Revisar liquido de dirección',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => '3500',
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:45:49',
                'modified' => '2017-03-14 18:45:49',
            ],
            [
                'id' => '111',
                'requests_type_id' => '1',
                'name' => 'Cambio de correa de dirección',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '10000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:47:29',
                'modified' => '2017-03-14 18:47:29',
            ],
            [
                'id' => '112',
                'requests_type_id' => '2',
                'name' => 'Rotación de neumáticos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:47:58',
                'modified' => '2017-03-14 18:47:58',
            ],
            [
                'id' => '113',
                'requests_type_id' => '3',
                'name' => 'Revisar presión de neumaticos',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:48:31',
                'modified' => '2017-03-14 18:48:31',
            ],
            [
                'id' => '114',
                'requests_type_id' => '3',
                'name' => 'Revisión rueda de repuesto',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:49:49',
                'modified' => '2017-03-14 18:49:49',
            ],
            [
                'id' => '115',
                'requests_type_id' => '1',
                'name' => 'Cambiar rueda de repuesto',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:50:22',
                'modified' => '2017-03-14 18:50:22',
            ],
            [
                'id' => '116',
                'requests_type_id' => '1',
                'name' => 'Reparación de neumático con tarugo',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '1000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:50:57',
                'modified' => '2017-03-14 18:50:57',
            ],
            [
                'id' => '117',
                'requests_type_id' => '3',
                'name' => 'Cambio de perno de rueda',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '1500',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:51:30',
                'modified' => '2017-03-14 18:51:30',
            ],
            [
                'id' => '118',
                'requests_type_id' => '2',
                'name' => 'Cambio de terminales de dirección',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => '20000',
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:52:12',
                'modified' => '2017-03-14 18:52:12',
            ],
            [
                'id' => '119',
                'requests_type_id' => '2',
                'name' => 'Cambio de amortiguadores delanteros (par)',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '75000',
                'supplies_price' => NULL,
                'replacements_price' => '45000',
                'mechanic_pay' => '30000',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:53:03',
                'modified' => '2017-03-14 18:53:03',
            ],
            [
                'id' => '120',
                'requests_type_id' => '2',
                'name' => 'Cambio de amortiguadores traseros (par)',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '68750',
                'supplies_price' => NULL,
                'replacements_price' => '55000',
                'mechanic_pay' => '27500',
                'active' => '1',
                'inspection' => '0',
                'created' => '2017-03-14 18:53:43',
                'modified' => '2017-03-14 18:53:43',
            ],
            [
                'id' => '121',
                'requests_type_id' => '3',
                'name' => 'Revisión y reparación de componentes de cardan',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:54:11',
                'modified' => '2017-03-14 18:54:11',
            ],
            [
                'id' => '122',
                'requests_type_id' => '3',
                'name' => 'Revisión de fuelles de homocinética',
                'description' => '',
                'estimated_time' => '1',
                'real_estimated_time' => '1',
                'total_price' => '25000',
                'supplies_price' => NULL,
                'replacements_price' => NULL,
                'mechanic_pay' => '10000',
                'active' => '1',
                'inspection' => '1',
                'created' => '2017-03-14 18:54:39',
                'modified' => '2017-03-14 18:54:39',
            ],
        ];

        $table = $this->table('available_services');
        $table->insert($data)->save();
    }
}
