<?php
use Migrations\AbstractSeed;

/**
 * Providers seed.
 */
class ProvidersSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'city_id' => '1',
                'commune_id' => '18',
                'name' => 'Broches Chile',
                'contact_name' => 'Camilo Sesto',
                'address' => 'bellavista 390',
                'dni' => '76598365-9',
                'phone' => '+56285663469',
                'email' => 'contacto@brocheschile.cl',
                'website' => 'www.brocheschile.cl',
                'active' => '1',
                'created' => '2017-02-28 14:36:33',
                'modified' => '2017-03-15 15:46:56',
            ],
            [
                'id' => '2',
                'city_id' => '1',
                'commune_id' => '24',
                'name' => 'DYM Chile',
                'contact_name' => 'Ricardo Arjona',
                'address' => 'Av la estrella 2390',
                'dni' => '76514853-6',
                'phone' => '+56244589763',
                'email' => 'contacto@dymchile.cl',
                'website' => 'www.dymchile.cl',
                'active' => '1',
                'created' => '2017-03-15 15:49:21',
                'modified' => '2017-03-15 15:49:21',
            ],
            [
                'id' => '3',
                'city_id' => '1',
                'commune_id' => '19',
                'name' => 'Adriazola Repuestos',
                'contact_name' => 'Felipe Camiroaga',
                'address' => 'Av. Las Industrias 10831',
                'dni' => '99581430-7',
                'phone' => '+56223503300',
                'email' => 'contacto@adriazolarepuestos.cl',
                'website' => 'www.adriazolarepuestos.cl',
                'active' => '1',
                'created' => '2017-03-15 17:22:43',
                'modified' => '2017-03-15 17:38:44',
            ],
            [
                'id' => '4',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Ciper S.A',
                'contact_name' => 'Alejandro Sanz',
                'address' => 'Av Brasil 23',
                'dni' => '79528730-2',
                'phone' => '+56226949600',
                'email' => 'contacto@ciper.cl',
                'website' => 'www.ciper.cl',
                'active' => '1',
                'created' => '2017-03-15 17:40:57',
                'modified' => '2017-03-15 17:40:57',
            ],
            [
                'id' => '5',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Repuestos Express S.A',
                'contact_name' => 'Juan Luis Guerra',
                'address' => 'Santa Rosa 812',
                'dni' => '96928530-4',
                'phone' => '+56 228371970',
                'email' => 'contacto@repuestosexpress.cl',
                'website' => 'www.repuestosexpress.cl',
                'active' => '1',
                'created' => '2017-03-15 17:44:42',
                'modified' => '2017-03-15 17:44:42',
            ],
            [
                'id' => '6',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Vigfor S.A',
                'contact_name' => 'Juan Antonio Labra',
                'address' => 'Coquimbo 558',
                'dni' => '',
                'phone' => '+56226355780',
                'email' => 'contacto@vigfor.cl',
                'website' => 'www.vigfor.cl',
                'active' => '1',
                'created' => '2017-03-15 17:48:56',
                'modified' => '2017-03-15 17:48:56',
            ],
            [
                'id' => '7',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Bolomey SpA',
                'contact_name' => 'Rozamel Fierro',
                'address' => 'Aldunate 1539',
                'dni' => '',
                'phone' => '+56226728735',
                'email' => 'contacto@bolomey.cl',
                'website' => 'www.bolomey.cl',
                'active' => '1',
                'created' => '2017-03-15 17:51:29',
                'modified' => '2017-03-15 17:51:29',
            ],
            [
                'id' => '8',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Indra',
                'contact_name' => 'Enrique Iglesias',
                'address' => 'Lira 664',
                'dni' => '',
                'phone' => '+56222805200',
                'email' => 'contacto@indra.cl',
                'website' => 'www.indra.cl',
                'active' => '1',
                'created' => '2017-03-15 17:56:39',
                'modified' => '2017-03-15 17:56:39',
            ],
            [
                'id' => '9',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'AD Repuestos',
                'contact_name' => 'Alex Hernandez',
                'address' => '',
                'dni' => '76314257-4',
                'phone' => '+56977764624',
                'email' => 'alex.21@live.cl',
                'website' => 'www.adrepuestos.cl',
                'active' => '1',
                'created' => '2017-03-15 18:00:04',
                'modified' => '2017-03-15 18:00:04',
            ],
            [
                'id' => '10',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Repuesto Center',
                'contact_name' => 'Jose Alfredo Fuentes',
                'address' => 'Alameda 1975',
                'dni' => '79656210-2',
                'phone' => '+56226344100',
                'email' => 'contact@repuestocenter.cl',
                'website' => 'www.repuestocenter.cl',
                'active' => '1',
                'created' => '2017-03-15 18:15:45',
                'modified' => '2017-03-15 18:15:45',
            ],
            [
                'id' => '11',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'MazHonda',
                'contact_name' => 'Alberto Plaza',
                'address' => '',
                'dni' => '',
                'phone' => '+56226341611',
                'email' => 'ventas@repuestosmazhonda.cl',
                'website' => 'www.repuestosmazhonda.cl',
                'active' => '1',
                'created' => '2017-03-15 18:17:16',
                'modified' => '2017-03-15 18:17:16',
            ],
            [
                'id' => '12',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'María Soto & Cia',
                'contact_name' => 'María Loreto Soto',
                'address' => '10 de Julio 478',
                'dni' => '77.459.190-7',
                'phone' => '+5622224183',
                'email' => 'contacto@repuestoshyundai.cl',
                'website' => 'www.repuestoshyundai.cl',
                'active' => '1',
                'created' => '2017-03-15 18:19:24',
                'modified' => '2017-03-15 18:19:24',
            ],
            [
                'id' => '13',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Ecomotor',
                'contact_name' => 'Luis Fonsi',
                'address' => 'Av. Brasil 41',
                'dni' => '',
                'phone' => '+56232026443',
                'email' => 'ventas@ecomotor.cl',
                'website' => 'www.ecomotor.cl',
                'active' => '1',
                'created' => '2017-03-15 18:22:33',
                'modified' => '2017-03-15 18:22:33',
            ],
            [
                'id' => '14',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Vimae',
                'contact_name' => 'Celia Cruz',
                'address' => '10 de Julio 618',
                'dni' => '79848180-0',
                'phone' => '+56226350145',
                'email' => 'contacto@vimae.cl',
                'website' => 'www.vimae.cl',
                'active' => '0',
                'created' => '2017-03-15 18:24:06',
                'modified' => '2017-03-15 18:24:06',
            ],
            [
                'id' => '15',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Nipon',
                'contact_name' => 'Myriam Hernandez',
                'address' => 'Claudio Gay 2539',
                'dni' => '',
                'phone' => '+56228288100',
                'email' => 'contacto@nipon.cl',
                'website' => 'www.nipon.cl',
                'active' => '1',
                'created' => '2017-03-15 18:25:27',
                'modified' => '2017-03-15 18:25:27',
            ],
            [
                'id' => '16',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Eterovic',
                'contact_name' => 'Mario Cariqueo',
                'address' => 'San Ignacio 1058',
                'dni' => '',
                'phone' => '+56226359167',
                'email' => 'mariocn@eterovic.cl',
                'website' => 'www.eterovic.wordpress.com',
                'active' => '1',
                'created' => '2017-03-15 18:27:12',
                'modified' => '2017-03-15 18:27:12',
            ],
            [
                'id' => '17',
                'city_id' => '1',
                'commune_id' => '1',
                'name' => 'Centro Wagen',
                'contact_name' => 'Fernando Ubiergo',
                'address' => '10 de Julio 535',
                'dni' => '',
                'phone' => '+56225793072',
                'email' => 'contacto@centrowagen.cl',
                'website' => 'www.centrowagen.cl',
                'active' => '1',
                'created' => '2017-03-15 18:28:45',
                'modified' => '2017-03-15 18:28:45',
            ],
        ];

        $table = $this->table('providers');
        $table->insert($data)->save();
    }
}
