#!/usr/bin/env ruby
#^syntax detection
site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'        , '~> 4.0.1'
cookbook 'nginx'      , '~> 2.7.6'
cookbook 'mysql'      , '~> 5.3.0'
cookbook 'php'        , '~> 1.9.0'
cookbook 'php-fpm'    , '~> 0.7.5'
cookbook 'git'        , '~> 4.5.0'
cookbook 'composer'   , '~> 2.3.0'
cookbook 'wkhtmltopdf',
  :git => 'https://github.com/geedelur/chef-wkhtmltopdf'
